name: Build libdave

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev nlohmann-json3-dev ninja-build

      - name: Build MLSPP first
        run: |
          cd cpp/third_party/mlspp
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          sudo cmake --install build

      - name: Build libdave
        run: |
          cd cpp
          cmake -B build -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libdave-linux
          path: cpp/build/**/*.so
