name: Build libdave

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libssl-dev ninja-build curl zip unzip tar pkg-config make

      - name: Init vcpkg submodule
        run: |
          git submodule update --init cpp/vcpkg

      - name: Bootstrap vcpkg
        run: |
          cd cpp
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      - name: Build shared library
        run: |
          cd cpp
          make shared

      - name: Find .so files
        run: |
          find ./cpp/build -name "*.so" 2>/dev/null

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libdave-linux
          path: cpp/build/**/*.so
